---
swagger: "2.0"
info:
  description: This is a Commentaries API
  version: 1.0.0
  title: AISS API
  contact:
    email: AISSproyect@AISSproyect.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: virtserver.swaggerhub.com
basePath: /proyecto-aiss/proyecto-aiss/1.0.0
tags:
- name: admins
  description: Secured Admin - only for privacy policy
- name: developers
  description: Operations available to regular developers
schemes:
- https
- http
paths:
  /commentaries/{id}:
    get:
      tags:
      - developers
      summary: searches commentary
      description: |
        By passing in the appropriate options, you can search for
        available commentary in the system
      operationId: searchCommentary
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        description: pass an optional search string for looking up commentary
        required: true
        type: string
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/CommentaryItem'
        400:
          description: bad input parameter
        404:
          description: not found
        default:
          description: unexpected error
    put:
      tags:
      - admins
      summary: change a commentary item
      description: |
        You can change for available commentary in the system
        if it doesn't comply with the privacy policy
      operationId: changeCommentary
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        description: pass an search string for looking up commentary and change it
        required: true
        type: string
      responses:
        204:
          description: no content
          schema:
            type: array
            items:
              $ref: '#/definitions/CommentaryItem'
        default:
          description: unexpected error
    delete:
      tags:
      - admins
      summary: delete a commentary item
      description: |
        You can delete for available commentary in the system
        if it doesn't comply with the privacy policy
      operationId: deleteCommentary
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        description: pass string for delete commentary
        required: true
        type: string
      responses:
        400:
          description: bad input parameter
        418:
          description: I'm a teapot
        default:
          description: unexpected error
  /commentaries:
    get:
      tags:
      - developers
      summary: searches commentaries
      description: |
        You can search for available commentaries in the system
      operationId: searchesCommentaries
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/CommentaryItem'
        404:
          description: not found
        default:
          description: unexpected error
    post:
      tags:
      - developers
      summary: adds a commentary item
      description: |
        Adds an item to the system
      operationId: addCommentary
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: commentaryItem
        description: Commentary item to add
        required: false
        schema:
          $ref: '#/definitions/CommentaryItem'
      responses:
        201:
          description: item created
        400:
          description: invalid input, object invalid
        409:
          description: an existing item already exists
        default:
          description: unexpected error
definitions:
  CommentaryItem:
    type: object
    required:
    - id
    - name
    properties:
      id:
        type: string
        format: uuid
        example: d290-6c54-4b01-90e6-d70174
      name:
        type: string
        example: The best party ever
      releaseDate:
        type: string
        format: date-time
        example: 2016-08-29T09:12:33.001Z
